language: node_js
node_js:
  - "6"
branches:
  only:
  - master
before_install:
  - npm config set progress false
install:
  - npm install -g firebase-tools
  - npm install
script:
  # lint on pull requests
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then grunt eslint; fi
  # build on merge, commit, whatever
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then grunt build_prod; fi
after_success:
  # ship to firebase on merge, commit, whatever to master
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then firebase deploy; fi
