language: node_js
node_js:
  - "6"
branches:
  only:
  - master
before_install:
  - npm config set progress false
install:
  - npm install -g firebase-tools
  - npm install
script:
  - grunt build
after_success:
  - firebase deploy
